* DONE Simulation [2/2]
  - [X] Sur quels types de machines sont généralement exécutées ces
    simulations? Supercalculateurs?
    Sur n'importe quel type de machine. C'est l'intérêt de la simulation.
  - [X] Comment la simulation peut-elle être plus rapide que le
    système réel? Cela s'applique t-il seulement avec l'approche
    offilne?
    Parce que tout n'est pas exécutes, certains traitements sont
    remplacés par un délais.
* TODO Simgrid [2/3]
  - [X] Acutellement quels types de programmes MPI sont testés sous
    Simgrid s'il n'y a pas la privatization entre le processus?
    Seulement des noeuds sur lesquelles tourne un seul processus MPI
    sur chacun.
  - [X] Pourquoi MSG et SMPI n'ont pas été prévu pour fonctionner
    ensemble? Essentiellement car le modèle de performance
    (communications CPU-GPU et réseau) et de programmation sont
    différents (mémoire partagée, mémoire distribuée).
  - [ ] Comment sont évaluées les performances des calculs coûteux
    effectués par les utilisateurs, manuellement, où il existe un
    mécanisme qui va évaluer la compléxité en temps d'une fonction?
* DONE StarPU [1/1]
  - [X] Où réside la difficulté de programmation des plateformes
    hybrid?
    Découpage des traitement déjà compliqué sans les GPU, encore pire avec.
